{
 "title": "Flink Dashboard",
 "description": "flink with prometheus",
 "tags": [ "flink" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "job_name",
    "label": "job_name",
    "query": "label_values(flink_taskmanager_job_task_numRecordsOutPerSecond, job_name)"
   }
  ]
 },
 "panels": [
  { "title": "Slots", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "# of TaskManagers",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "flink_jobmanager_numRegisteredTaskManagers",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Taskslots available",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "flink_jobmanager_taskSlotsAvailable"
    }
   ]
  },
  {
   "title": "# of Running Jobs",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "flink_jobmanager_numRunningJobs",
     "legendFormat": "{{instance}} jobmanager运行的job数量"
    }
   ]
  },
  {
   "title": "Taskslots total",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "flink_jobmanager_taskSlotsTotal"
    }
   ]
  },
  { "title": "BackPressure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "inPoolUsag",
   "type": "graph",
   "description": "inPoolUsag",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_Shuffle_Netty_Input_Buffers_inPoolUsage{job_name=~\"$job_name\"}) by (job_name)",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "outPoolUsage",
   "type": "graph",
   "description": "outPoolUsage",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_Shuffle_Netty_Output_Buffers_outPoolUsage{job_name=~\"$job_name\"}) by (job_name)",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "outputQueueLength",
   "type": "graph",
   "description": "outputQueueLength",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_Shuffle_Netty_Output_Buffers_outputQueueLength{job_name=~\"$job_name\"}) by (job_name)",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "numRecordsOutPerSecond",
   "type": "graph",
   "description": "numRecordsOutPerSecond",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_numRecordsOutPerSecond{job_name=~\"$job_name\"}) by (job_name, operator_name)",
     "legendFormat": "{{job_name}}_{{subtask_index}}_{{operator_name}}_RecordsOutPerSecond"
    }
   ]
  },
  {
   "title": "numRecordsInPerSecond",
   "type": "graph",
   "description": "umRecordsInPerSecond",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_numRecordsInPerSecond{job_name=~\"$job_name\"}) by (job_name)",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "inputQueueLength",
   "type": "graph",
   "description": "inputQueueLength",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_Shuffle_Netty_Input_Buffers_inputQueueLength{job_name=~\"$job_name\"}",
     "legendFormat": "{{job_name}}_{{subtask_index}}_{{task_attempt_id}}_inputQueueLength"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "TaskManager Garbage Collection count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(flink_taskmanager_Status_JVM_GarbageCollector_Copy_Count[1m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "TaskManagers Garbage Collection Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "delta(flink_taskmanager_Status_JVM_GarbageCollector_Copy_Time[1m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "live Thread count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_Threads_Count",
     "legendFormat": "{{host}} jobManager live Thread counts"
    },
    {
     "expr": "flink_taskmanager_Status_JVM_Threads_Count",
     "legendFormat": "{{host}} taskManger live Thread counts"
    }
   ]
  },
  { "title": "CheckPoint", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "lastCheckpointDuration",
   "type": "graph",
   "description": "lastCheckpointDuration",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "increase(flink_jobmanager_job_lastCheckpointDuration{job_name=~\"$job_name\"}[2m])",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "Last CheckPoint Size",
   "type": "graph",
   "description": "Last CheckPoint Size",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "increase(flink_jobmanager_job_lastCheckpointSize{job_name=~\"$job_name\"}[2m])",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "numberOfFailedCheckpoints",
   "type": "graph",
   "description": "numberOfFailedCheckpoints",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(flink_jobmanager_job_numberOfFailedCheckpoints{job_name=~\"$job_name\"}[2m])",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  { "title": "connector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "offset commit failures to Kafka",
   "type": "graph",
   "description": "offset commit failures to Kafka",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(flink_taskmanager_job_task_operator_commitsFailed{job_name=~\"$job_name\"}[2m])",
     "legendFormat": "{{host}}-{{job_name}}"
    }
   ]
  },
  {
   "title": "records has dropped due to arriving late.",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(flink_taskmanager_job_task_operator_numLateRecordsDropped{job_name=~\"$job_name\"}[1m])",
     "legendFormat": "{{host}}_{{job_name}}_{{tm_id}}"
    }
   ]
  },
  {
   "title": "job-downtime",
   "type": "graph",
   "description": "job-downtime",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 34 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_job_downtime{job_name=~\"$job_name\"}",
     "legendFormat": "{{host}}_{{job_name}}_downtime"
    }
   ]
  },
  { "title": "rocksdb", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "block cache usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_fire_time_rocksdb_block_cache_usage{job_name=~\"$job_name\"}) by (job_name)",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "num running compactions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator__timer_state_event_window_timers_rocksdb_num_running_compactions{job_name=~\"$job_name\"}) by (job_name)",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "num running flushes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator__timer_state_event_window_timers_rocksdb_num_running_flushes{job_name=~\"$job_name\"}) by (job_name)",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  { "title": "IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "JobManager Memory Available",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_Heap_Max-flink_jobmanager_Status_JVM_Memory_Heap_Used",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "TaskManager Memory Available",
   "type": "graph",
   "description": "TaskManager Memory Available",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 48 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Heap_Max-flink_taskmanager_Status_JVM_Memory_Heap_Used",
     "legendFormat": "{{host}}:{{tm_id}}"
    }
   ]
  },
  {
   "title": "JobManager NonHeap Memory Available",
   "type": "graph",
   "description": "JobManager NonHeap Memory Available",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 48 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_NonHeap_Committed-flink_jobmanager_Status_JVM_Memory_NonHeap_Used",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "TaskManger NonHeap Memory Available",
   "type": "graph",
   "description": "TaskManger NonHeap Memory Available",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_NonHeap_Committed-flink_taskmanager_Status_JVM_Memory_NonHeap_Used",
     "legendFormat": "{{host}}:{{tm_id}}"
    }
   ]
  }
 ]
}