{
 "title": "MSK & Connect Overview",
 "description": "Prometheus monitoring for MSK cluster",
 "tags": [
  "msk",
  "kafka",
  "connect"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Kafka Connect", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Connectors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cp_kafka_connect_connect_worker_metrics_connector_count"
    }
   ]
  },
  {
   "title": "Number of Tasks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(cp_kafka_connect_connect_worker_metrics_task_count)"
    }
   ]
  },
  {
   "title": "Connector Startup Success Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(cp_kafka_connect_connect_worker_metrics_connector_startup_success_total)"
    }
   ]
  },
  {
   "title": "Connector Startup Failure Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(cp_kafka_connect_connect_worker_metrics_connector_startup_failure_total)"
    }
   ]
  },
  {
   "title": "Task Startup Success Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(cp_kafka_connect_connect_worker_metrics_task_startup_success_total)"
    }
   ]
  },
  {
   "title": "Task Startup Failure Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(cp_kafka_connect_connect_worker_metrics_task_startup_failure_total)"
    }
   ]
  },
  {
   "title": "Connect Metrics: IO Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cp_kafka_connect_connect_metrics_connect_1_io_ratio",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Connect Metrics: Incoming Byte Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cp_kafka_connect_connect_metrics_connect_1_incoming_byte_rate",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Connect Metrics: Network IO Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Computation" } },
   "yaxes": [
    { "format": "Computation" }
   ],
   "targets": [
    {
     "expr": "cp_kafka_connect_connect_metrics_connect_1_network_io_rate",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"connect\", pod=~\"cp-kafka-connect-.+\", container!=\"POD\", container!=\"\", image!=\"\"}) by (container, pod)",
     "legendFormat": "{{container}} ({{pod}})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"connect\", pod=~\"cp-kafka-connect.*\", container!=\"POD\"}) by (container, pod)",
     "legendFormat": "{{container}} {{pod}}"
    }
   ]
  },
  {
   "title": "Connector Tasks Status Per POD",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cp_kafka_connect_connect_connector_metrics) by (connector, status, pod)",
     "legendFormat": "{{connector}} ({{pod}}) - {{status}}"
    }
   ]
  },
  { "title": "MSK Per Topic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Messages In Per Sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_BrokerTopicMetrics_Count{name=\"MessagesInPerSec\", topic=~\".+\"}[1m])) by(topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Sec from Clients",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_BrokerTopicMetrics_Count{name=\"BytesInPerSec\", topic=~\".+\"}[1m])) by(topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_BrokerTopicMetrics_Count{name=\"BytesOutPerSec\", topic=~\".+\"}[1m])) by(topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "MSK Per Broker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Under Replicated Partitions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (kafka_server_ReplicaManager_Value{name=\"UnderReplicatedPartitions\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Under ISR Partitions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_ReplicaManager_Value{name=\"UnderMinIsrPartitionCount\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Partition Counts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_ReplicaManager_Value{name=\"PartitionCount\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(kafka_network_RequestMetrics_Count{name=\"RequestsPerSec\", request=~\"Produce|FetchConsumer|FetchFollower\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(kafka_network_RequestMetrics_Count{name=\"ErrorsPerSec\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}