{
 "title": "Spring Boot HikariCP / JDBC Copy",
 "description": "HikariCP & JDBC Dashboard (Micrometer.io)",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "application",
    "label": "Application",
    "query": "label_values(hikaricp_connections_min, application)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(hikaricp_connections_min{application=\"$application\"}, instance)"
   },
   {
    "name": "hikaricp_pool_name",
    "label": "Hikari  Pool Name",
    "query": "label_values(hikaricp_connections_min{application=\"$application\", instance=~\"$instance\"}, pool)"
   }
  ]
 },
 "panels": [
  { "title": "JDBC Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Min",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(hikaricp_connections_min{application=\"$application\", instance=~\"$instance\", pool=\"$hikaricp_pool_name\"})"
    }
   ]
  },
  {
   "title": "Active",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(hikaricp_connections_active{application=\"$application\", instance=~\"$instance\", pool=\"$hikaricp_pool_name\"})"
    }
   ]
  },
  {
   "title": "Max",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(hikaricp_connections_max{application=\"$application\", instance=~\"$instance\",  pool=\"$hikaricp_pool_name\"})"
    }
   ]
  },
  { "title": "Hikari Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 12, "w": 21, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_active{application=\"$application\", instance=~\"$instance\", pool=~\"$hikaricp_pool_name\"}",
     "legendFormat": "Active connections"
    },
    {
     "expr": "hikaricp_connections_idle{application=\"$application\", instance=~\"$instance\", pool=~\"$hikaricp_pool_name\"}",
     "legendFormat": "Idle connections"
    },
    {
     "expr": "hikaricp_connections_pending{application=\"$application\", instance=~\"$instance\", pool=~\"$hikaricp_pool_name\"}",
     "legendFormat": "Pending threads"
    }
   ]
  },
  {
   "title": "Max",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(hikaricp_connections_max{application=\"$application\", instance=~\"$instance\", pool=~\"$hikaricp_pool_name\"})"
    }
   ]
  },
  {
   "title": "Min",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(hikaricp_connections_min{application=\"$application\", instance=~\"$instance\", pool=~\"$hikaricp_pool_name\"})"
    }
   ]
  },
  {
   "title": "Total Timeout",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(hikaricp_connections_timeout_total{application=\"$application\", instance=~\"$instance\", pool=~\"$hikaricp_pool_name\"})"
    }
   ]
  },
  {
   "title": "Connections Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "irate(hikaricp_connections_usage_seconds_sum{application=\"$application\", instance=~\"$instance\", pool=~\"$hikaricp_pool_name\"}[5m]) / irate(hikaricp_connections_usage_seconds_count{application=\"$application\", instance=~\"$instance\", pool=~\"$hikaricp_pool_name\"}[5m])",
     "legendFormat": "Usage time"
    },
    {
     "expr": "irate(hikaricp_connections_creation_seconds_sum{application=\"$application\", instance=~\"$instance\", pool=~\"$hikaricp_pool_name\"}[5m]) / irate(hikaricp_connections_creation_seconds_count{application=\"$application\", instance=~\"$instance\", pool=~\"$hikaricp_pool_name\"}[5m])",
     "legendFormat": "Creation time"
    },
    {
     "expr": "irate(hikaricp_connections_acquire_seconds_sum{application=\"$application\", instance=~\"$instance\", pool=~\"$hikaricp_pool_name\"}[5m]) / irate(hikaricp_connections_acquire_seconds_count{application=\"$application\", instance=~\"$instance\", pool=~\"$hikaricp_pool_name\"}[5m])",
     "legendFormat": "Acquire time"
    }
   ]
  }
 ]
}